/**
 * This file was generated by the Jeddict
 */
package schoolmanagementproject.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * @author mehtab kayani
 */
@NamedQueries({
    @NamedQuery(name = "showAllC",query=("Select a From Course a")),
})
@Entity
public class Course {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Basic
    private String name;

    @ManyToMany(mappedBy = "courses")
    private List<Education> educations;

    @ManyToMany(fetch = FetchType.EAGER)
    private List<Teacher> teachers;

    public Course() {
    }

    public Course(String name) {
        this.name = name;
    }
    
    

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Education> getEducations() {
        if (educations == null) {
            educations = new ArrayList<>();
        }
        return this.educations;
    }

    public void setEducations(List<Education> educations) {
        this.educations = educations;
    }

    public void addEducation(Education education) {
        getEducations().add(education);
    }

    public void removeEducation(Education education) {
        getEducations().remove(education);
    }

    public List<Teacher> getTeachers() {
        if (teachers == null) {
            teachers = new ArrayList<>();
        }
        return this.teachers;
    }

    public void setTeachers(List<Teacher> teachers) {
        this.teachers = teachers;
    }

    public void addTeacher(Teacher teacher) {
        getTeachers().add(teacher);
        teacher.getCourses().add(this);
    }

    public void removeTeacher(Teacher teacher) {
        getTeachers().remove(teacher);
        teacher.getCourses().remove(this);
    }

    @Override
    public String toString() {
        ArrayList<String> names = new ArrayList<>();
        for (Teacher t : teachers) {
            names.add(t.getName());
        }

        return "Course{" + "id=" + id + ", name=" + name + names ;
    }

}