/**
 * This file was generated by the Jeddict
 */
package schoolmanagementproject.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

/**
 * @author mehtab kayani
 */
@NamedQueries({
    @NamedQuery(name= "showAllE",query = ("Select a From Education a")),
})
@Entity
public class Education {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Basic
    private String name;

    @OneToMany(mappedBy = "education", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    private List<Student> students;

    @ManyToMany( fetch = FetchType.EAGER)
    private List<Course> courses;

    public Education() {
    }

    public Education(String name) {
        this.name = name;
    }
    
    

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Student> getStudents() {
        if (students == null) {
            students = new ArrayList<>();
        }
        return this.students;
    }

    public void setStudents(List<Student> students) {
        this.students = students;
    }

    public void addStudent(Student student) {
        getStudents().add(student);
        student.setEducation(this);
    }

    public void removeStudent(Student student) {
        getStudents().remove(student);
        student.setEducation(null);
    }

    public List<Course> getCourses() {
        if (courses == null) {
            courses = new ArrayList<>();
        }
        return this.courses;
    }

    public void setCourses(List<Course> courses) {
        this.courses = courses;
    }

    public void addCourse(Course course) {
        getCourses().add(course);
        course.getEducations().add(this);
    }

    public void removeCourse(Course course) {
        getCourses().remove(course);
        course.getEducations().remove(this);
    }

    @Override
    public String toString() {
        ArrayList<String> names = new ArrayList<>();
        for (Student s : students) {
            names.add(s.getName());
            
        }
        ArrayList<String> namesC = new ArrayList<>();
        for (Course c : courses) {
            namesC.add(c.getName());
        }
        return "Education ID: " + id + ", name: " + name + ", students: " + names + ", courses: " + namesC;
    }
    
    

}